[package]
name = "traktor-gql"
version = "0.1.0"
authors = ["Jacob Haslehurst <jacob@haslehurst.net>"]

[dependencies]
xml-rs = "0.4"
juniper = { version = "*", features = ["iron-handlers"] }
mount = "*"
iron = "*"
persistent = "*"
